"""test

Revision ID: 7ae43eabc408
Revises: e1aabb5b3d58
Create Date: 2025-09-08 13:30:40.486319

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ae43eabc408"
down_revision: Union[str, Sequence[str], None] = "e1aabb5b3d58"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("media", sa.Column("test", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("media", "test")
    # ### end Alembic commands ###
