"""initial_migration

Revision ID: e1aabb5b3d58
Revises:
Create Date: 2025-09-08 13:27:44.139241

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e1aabb5b3d58"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # noqa: PIE790
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # noqa: PIE790
    # ### end Alembic commands ###
